application: wimylime
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.htm
  upload: index.htm

- url: /recorder.htm
  static_files: recorder.htm
  upload: recorder.htm

- url: /player.htm
  static_files: player.htm
  upload: player.htm
  
- url: /style.css
  static_files: style.css
  upload: style.css
  
- url: /youtube.js
  static_files: youtube.js
  upload: youtube.js

- url: /recorder.js
  static_files: youtube.js
  upload: youtube.js

- url: /player.js
  static_files: youtube.js
  upload: youtube.js

- url: /common.js
  static_files: common.js
  upload: common.js
  
- url: /images/note1.png
  static_files: images/note1.png
  upload: images/note1.png
  
- url: /images/note2.png
  static_files: images/note2.png
  upload: images/note2.png
  
- url: /images/note3.png
  static_files: images/note3.png
  upload: images/note3.png
  
- url: /images/note4.png
  static_files: images/note4.png
  upload: images/note4.png
  
- url: /images/note1pop.png
  static_files: images/note1pop.png
  upload: images/note1pop.png
  
- url: /images/note2pop.png
  static_files: images/note2pop.png
  upload: images/note2pop.png
  
- url: /images/note3pop.png
  static_files: images/note3pop.png
  upload: images/note3pop.png
  
- url: /images/note4pop.png
  static_files: images/note4pop.png
  upload: images/note4pop.png
  

